FROM python:3.12-slim

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY app ./app
COPY mcp_servers ./mcp_servers

EXPOSE 8001

CMD uv run python mcp_servers/github_mcp/server.py